export const Images = {
    xhero_right: require('../Assests/Images/xhero_right.png.pagespeed.ic.U76_mb-Zcf.webp').default,
    visit_jpg: require('../Assests/Images/visit.jpg.webp').default,
    xgallery1: require('../Assests/Images/xgallery1.jpg.pagespeed.ic.4S3RPoxrB5.webp').default,
    xgallery2: require('../Assests/Images/xgallery2.jpg.pagespeed.ic.-N60ar7LLo.webp').default,
    xgallery4: require('../Assests/Images/xgallery4.jpg.pagespeed.ic.fflSVOffX7.webp').default,
    xsingle_blog_1: require('../Assests/Images/xsingle_blog_1.jpg.pagespeed.ic.crhqX85fp0.webp').default,
    xsingle_blog_2: require('../Assests/Images/xsingle_blog_2.jpg.pagespeed.ic.QwFRAzu_NP.webp').default,
    xsingle_blog_3: require('../Assests/Images/xsingle_blog_3.jpg.pagespeed.ic.D3so3ZMyuT.webp').default,
    xsingle_blog_4: require('../Assests/Images/xsingle_blog_4.jpg.pagespeed.ic.sPLUurA5SD.webp').default,
    xsingle_blog_5: require('../Assests/Images/xsingle_blog_5.jpg.pagespeed.ic.iAJ-fvqdoP.webp').default,
    post_1_jpg: require('../Assests/Images/post_1.jpg.webp').default,
    post_2_jpg: require('../Assests/Images/post_2.jpg.webp').default,
    post_3_jpg: require('../Assests/Images/post_3.jpg.webp').default,
    post_4_jpg: require('../Assests/Images/post_4.jpg.webp').default,
    xpost_5: require('../Assests/Images/xpost_5.jpg.pagespeed.ic.6uccBsOBRz.webp').default,
    xpost_6: require('../Assests/Images/xpost_6.jpg.pagespeed.ic.BgB7ZoApSh.webp').default,
    xpost_7: require('../Assests/Images/xpost_7.jpg.pagespeed.ic.zr6b7EBuiM.webp').default,
    xpost_8: require('../Assests/Images/xpost_8.jpg.pagespeed.ic.r2dZPIfpQ6.webp').default,
    xpost_9: require('../Assests/Images/xpost_9.jpg.pagespeed.ic.XAu-nZ8b4Z.webp').default,
    xpost_10: require('../Assests/Images/xpost_10.jpg.pagespeed.ic.VbUYrTwO92.webp').default,
}
